config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_lists, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :receivers, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get 'orders/about' => 'orders#about', as: 'orders_about'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm'
    
    resource :customers, only: [:show, :edit, :update]
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/confirm' => 'customers#confirm'
  end

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_lists

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]

  def add_tax_price
    (price * 1.1).floor
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
      flash[:notice] = "商品を追加しました。"
    else
      flash.now[:alert] = "全ての項目が必須入力です。"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "変更が保存されました。"
      redirect_to admin_item_path
    else
    flash.now[:alert] = "全ての項目が必須入力です。"
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :image, :name, :introduction, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <div class="position-center">
        <h4><span class="page-title">商品編集</span></h4>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto md-5">
      <%= form_with model: ([:admin,@item]), local: true do |f| %>
      <table class=" table-center table-form">
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.attachment_field :image %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <th><%= f.text_field :name, placeholder:"商品名", size: 47 %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <th><%= f.text_area :introduction, size: "50×5", placeholder:"ここに説明文を記述します" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <th><%= f.collection_select :genre_id, Genre.all, :id, :name %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :税抜き価格 %></th>
            <th><%= f.text_field :price, placeholder:"1000", size: 47 %>円</th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :販売ステータス %></th>
            <th>　<%=f.radio_button :is_active, :true %><span class="text-green"> 販売中</span>　　<%=f.radio_button :is_active, :false %><span class="text-silver"> 販売中止中</span></th>
          </div>
        </tr>
        <tr>
          <div class="form-action">
            <th><%= f.submit "変更を保存", class: "btn btn-success" %></th>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class = "container o-8column">
  <div class = "row mx-auto">
    
    <div class="col-md-10">
      <div class="position-center">
        <h4><span class="page-title items">商品一覧</span></h4>
      </div>
    </div>

     <div class="col-md-2">
      <p class="new-item"><%= link_to "新規商品作成", new_admin_item_path, class: "btn btn-outline-secondary" %></p>
     </div>
  </div>

  <div class="container">
    <table class="table">
      <thead class="thead-light">
        <div class ="row justify-content-center">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </div>
      </thead>
      <tbody>
      <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item) %></td>
            <td class="text-right"><%= item.price.to_s(:delimited) %>円</td>
            <td class="text-center"><%= item.genre.name %></td>
            <td class="text-center">
              <% if item.is_active == false %>
                <span class="text-silver">販売停止中</span>
              <% else %>
                <span class="text-green">販売中</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='textcenter' ><%= paginate @items, theme: 'twitter-bootstrap-4' %></div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <div class="position-center">
        <h4><span class="page-title">商品新規登録</span></h4>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto md-5">
      <%= form_with model: ([:admin,@item]), local: true do |f| %>
      <table class=" table-center table-form">
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <td><%= f.attachment_field :image %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td colspan="2"><%= f.text_field :name, placeholder:"商品名", size: 47 %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td colspan="2"><%= f.text_area :introduction, size: "50×5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <td colspan="2"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :税抜き価格 %></th>
            <td colspan="2"><%= f.text_field :price, placeholder:"1000", size: 47 %>円</td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :販売ステータス %></th>
            <td>　<%=f.radio_button :is_active, :true, checked: true %> 販売中　　<%=f.radio_button :is_active, :false %> 販売停止中</td>
          </div>
        </tr>
        <tr>

          <div class="form-action ">
            <th></th>
            <td><%= f.submit "新規登録", class: "btn btn-success" %></th>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
  <div class = "row mt-5">
    <div class="position-center">
      <h4><span class="page-title">商品詳細</span></h4>
    </div>
  </div>

  <div class = "row mt-5">
    <div class = "col-md-4">
      <%= attachment_image_tag @item, :image, :fill, 300, 300, fallback:"no_image.jpeg", size: "300x300"  %>
    </div>

    <div class = "col-md-8">
      <table class = "table-form">
        <tr>
          <th class="column-narrow">商品名</th>
          <td class="column-very-wide"><%= @item.name %></td>
        </tr>

        <tr>
          <th class="column-narrow">商品説明</th>
          <td class="column-very-wide"><%= @item.introduction %></td>
        </tr>

        <tr>
          <th class="column-narrow">ジャンル</th>
          <td class="column-very-wide"><%= @item.genre.name %></td>
        </tr>

        <tr>
          <th class="column-narrow">
            税込価格</br>(税抜価格)
          </th>
          <td class="column-very-wide">
            <%= @item.add_tax_price.to_s(:delimited, delimiter: ',') %>  円<br>
            (<%= @item.price %>)円
          </td>
        </tr>

        <tr>
          <th class="column-narrow">販売ステータス</th>
          <td class="column-very-wide">
            <% if @item.is_active == false %>
            <span class="text-silver">販売停止中</span>
            <% else %>
            <span class="text-green">販売中</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="column-narrow"></th>
          <td class="column-very-wide"><%= link_to "編集する",edit_admin_item_path(@item.id), class: "btn btn-success" %></td>
        </tr>
      </table>

    </div>
  </div>
</div>