config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_lists, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :receivers, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get 'orders/about' => 'orders#about', as: 'orders_about'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm'
    
    resource :customers, only: [:show, :edit, :update]
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/confirm' => 'customers#confirm'
  end

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :receivers, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true

  def active_for_authentication?
    # is_deletedがfalseならtrueを返すようにしています。
    super && (self.is_deleted == false)
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
      flash[:notice] = "変更内容を保存しました。"
    else
      flash.now[:alert] = "全ての項目が必須入力です。"
      render :edit
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="position-center">
  <h4><span class="page-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span></h4>
</div>
<span class="space"></span>

<%= form_with model:@customer, url: admin_customer_path, local:true do |f| %>
  <table class="table-center table-form">
    <tr>
      <th class="column-narrow">会員ID</th>
      <td class="column-wide"><%= f.label :"#{@customer.id}" %></td>
      <td class="column-wide"></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"氏名" %></th>
      <td class="column-wide"><%= f.text_field :last_name %></td>
      <td class="column-wide"><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"フリガナ" %></th>
      <td class="column-wide"><%= f.text_field :last_name_kana %></td>
      <td class="column-wide"><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"郵便番号" %></th>
      <td class="column-wide"><%= f.text_field :postal_code %></td>
      <td class="column-wide"></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"住所" %></th>
      <td class="column-very-wide" colspan="2"><%= f.text_field :address, size: 55 %></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"電話番号" %></th>
      <td class="column-wide"><%= f.text_field :phone_number %></td>
      <td class="column-wide"></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"メールアドレス" %></th>
      <td class="column-wide"><%= f.email_field :email %></td>
      <td class="column-wide"></td>
    </tr>
    <tr>
      <th class="column-narrow"><%= f.label :"会員ステータス" %></th>
      <td class="column-wide"><!--is_deletedをfalseに変更するボタン-->
      <%= f.radio_button :is_deleted, :false %>
      <%= f.label :is_deleted, "有効　　" %>
      <!--is_deletedをtrueに変更するボタン-->
      <%= f.radio_button :is_deleted, :true %>
      <%= f.label :is_deleted, "退会" %></td>
      <td class="column-wide"></td>
    </tr>
    <tr>
      <th class="column-wide"></th>
      <td class="column-wide"><%= f.submit"変更を保存", class: "btn btn-success" %></td>
      <td class="column-wide"></td>
    </tr>
  </table>
<%end%>

app/views/admin/customers/index.html.erb
<div class="position-center">
  <div class="space"></div>
  <h4><span class="page-title">会員一覧</span></h4>
</div>

<table class='table-center'>
  <thead>
    <tr bgcolor="#C0C0C0">
      <th class="th-color">会員ID</th>
      <th class="th-color">氏名</th>
      <th class="th-color">メールアドレス</th>
      <th class="th-color">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |c| %>
      <tr>
        <td class="column-narrow text-center"><%= c.id %></td>
        <td class="column-narrow text-center"><%= link_to admin_customer_path(c.id) do %>
              <%= c.last_name + c.first_name %>
            <%end%>
        </td>
        <td class="column-wide text-center"><%= c.email %></td>
        <% if c.is_deleted == true %>
          <td class="column-narrow text-center"><span class="text-silver">退会</span></td>
        <%else%>
          <td class="column-narrow text-center"><span class="text-green">有効</span></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="position-center">
  <h4><span class="page-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h4>
</div>
<span class="space"></span>

<table class='table-center table-form'>

  <tbody>
    <tr>
      <th>会員ID</th>
      <td class="column-very-wide"><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td class="column-very-wide"><%= @customer.last_name %><%""%><%= @customer.first_name %></td>
    </tr>
    <tr>
       <th>フリガナ</th>
       <td class="column-very-wide"><%= @customer.last_name_kana %><%""%><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td class="column-very-wide"><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td class="column-very-wide"><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td class="column-very-wide"><%= @customer.phone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td class="column-very-wide"><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <!--is_deletedがtrueの場合は「退会」そうでなければ「有効」を表示する。-->
      <% if @customer.is_deleted == true %>
        <td class="column-very-wide">退会</td>
      <%else%>
        <td class="column-very-wide text-green">有効</td>
      <%end%>
    </tr>
  </tbody>
</table>

<div class="position-center">
<%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>　　　<%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>
</div>