config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_lists, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :receivers, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get 'orders/about' => 'orders#about', as: 'orders_about'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm'
    
    resource :customers, only: [:show, :edit, :update]
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/confirm' => 'customers#confirm'
  end

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_lists, dependent: :destroy
  
  validates :payment_method, presence: true
  validates :receiver_name, presence: true
  validates :receiver_postal_code, presence: true
  validates :receiver_address, presence: true
  
  #支払方法
  enum payment_method: { credit_card: 0, transfer: 1 }
  #注文ステータス
  enum order_status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }
  
def add_tax_price
　(price * 1.1).floor
end
  
def subtotal
    item.add_tax_price * quantity
end
  
end 

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)

    # 注文ステータスを選択したデータを取得が左辺
    # orderモデルのorder_statusの値を取得している。
    # 取得したデータが右辺の場合、その処理
    if params[:order][:order_status] == "paid_up"
      # 制作ステータスが自動で更新される（この記述は1＝”制作待ち”）
      @order.order_lists.update(making_status: 1)
    end
    redirect_back(fallback_location: root_path)


  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="position-center">
    <h4><span class="page-title">注文履歴一覧</span></h4>
  </div>

  <table class="table-center">
    <thead>
      <tr>
        <th class="th-color">購入日時</th>
        <th class="th-color">購入者</th>
        <th class="th-color">注文個数</th>
        <th class="th-color">注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
　　　　<!--日付と時間を表記-->
        <td class="column-wide text-center">
          <%= link_to admin_order_path(order.id) do %>
            <%= order.created_at.strftime('%Y年%m月%d日　%H:%M')  %>
          <% end %>
        </td>
        <td class="column-wide text-center"><%= order.customer.last_name + order.customer.first_name %></td>
        <td class="column-wide text-center">
          <!--each文内にあるためコントローラーを通らないのでビューページに記入することで注文ごとに0に戻す-->
          <% @total_quantity = 0 %>
          <% order.order_lists.each do |order_list| %>
          <!--商品の合計を足している-->
          <% @total_quantity += order_list.quantity %>
          <% end %>
          <!--足した値を表示-->
          <%= @total_quantity %> 個
        </td>
        <td class="column-wide text-center"><%= order.order_status_i18n %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/orders/show.html.erb
<div class="position-center">
  <h4><span class="page-title">注文履歴詳細</span></h4>
</div>

  <table class="table-center table-form">
    <tbody>
      <tr>
        <th class="column-narrow">購入者</th>
        <td class="column-wide"><%= @order.customer.last_name + " " + @order.customer.first_name %></td>
      </tr>
      <tr>
        <th class="column-narrow">注文日</th>
        <td class="column-wide"><%= @order.created_at.strftime("%Y年%m月%d日") %></td>
      </tr>
      <tr>
        <th class="column-narrow">配送先</th>
        <td class="column-wide">
          〒<%= @order.receiver_postal_code %><br>
          <%= @order.receiver_address %><br>
          <%= @order.receiver_name %>
        </td>
      </tr>
      <tr>
        <th class="column-narrow">支払方法</th>
        <td class="column-wide"><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th class="column-narrow">注文ステータス</th>
        <td class="column-wide">
          <%= form_with model: ([:admin, @order]), url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :order_status, Order.order_statuses_i18n.invert, {prompt: 0} %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table-center">
    <thead>
      <tr>
        <th class="th-color column-wide">商品名</th>
        <th class="th-color column-wide">単価（税込）</th>
        <th class="th-color column-narrow">数量</th>
        <th class="th-color column-narrow">小計</th>
        <th class="th-color column-wide">制作ステータス</th>
        <th class="th-color column-narrow"></th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_lists.each do |order| %>
        <tr>
          <td>　<%= order.item.name %></td>
          <td class="text-right"><%= order.item.add_tax_price.to_s(:delimited) %> 円</td>
          <td class="text-right"><%= order.quantity %> 個</td>
          <td class="text-right"><%= order.total_price.to_s(:delimited) %> 円</td>
          <!--form_withの全てを<td></td>または<th></th>の中に記載しないとリロードしないと機能しない-->

              <td class="text-center">
                <%= form_with model: ([:admin, order]), url: admin_order_list_path(order), local: true do |f| %>
                  <%= f.select :making_status, OrderList.making_statuses_i18n.invert, {prompt: 0} %>
                  <%= f.submit "更新", class: "btn btn-success" %>
                <% end %>
              </td>
        </tr>
      <% end %>
    </tbody>
  </table>

    <table class="table-right table-form">
      <tbody>
        <tr>
          <th class="column-wide bold">商品合計</th>
          <td class="column-narrow text-right"><%= @order.total_item_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th class="column-wide bold">送料</th>
          <td class="column-narrow text-right"><%= @order.delivery_fee.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th class="column-wide bold">請求金額合計</th>
          <td class="column-narrow text-right bold"><%= (@order.total_item_price + @order.delivery_fee).to_s(:delimited) %>円</td>
        </tr>
      </tbody>
    </table>