config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_lists, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :receivers, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    get 'orders/about' => 'orders#about', as: 'orders_about'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm'
    
    resource :customers, only: [:show, :edit, :update]
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/confirm' => 'customers#confirm'
  end

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  validates :quantity, presence: true
  
  #税込み価格用
  def add_tax_price
   (price * 1.1).floor
  end
  
  #小計算出用
  def subtotal
    item.add_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :receivers, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true

  def active_for_authentication?
    # is_deletedがfalseならtrueを返すようにしています。
    super && (self.is_deleted == false)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_lists

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]

  def add_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_lists, dependent: :destroy
  
  validates :payment_method, presence: true
  validates :receiver_name, presence: true
  validates :receiver_postal_code, presence: true
  validates :receiver_address, presence: true
  
  #支払方法
  enum payment_method: { credit_card: 0, transfer: 1 }
  #注文ステータス
  enum order_status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }
  
def add_tax_price
　(price * 1.1).floor
end
  
def subtotal
    item.add_tax_price * quantity
end
  
end 

app/models/order_list.rb
class OrderList < ApplicationRecord

  belongs_to :order
  belongs_to :item


  enum making_status: {not_startable: 0, wating_for_make: 1, making: 2, completed: 3 }

end

app/models/receiver.rb
class Receiver < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  
  #配送情報を全て表示するためのメソッド
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(8)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました。"
    else
      @genres = Genre.all.page(params[:page]).per(8)
      flash.now[:alert] = "ジャンル名を入力してください。"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を変更しました。"
    else
      flash.now[:alert] = "ジャンル名を入力してください。"
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
      flash[:notice] = "商品を追加しました。"
    else
      flash.now[:alert] = "全ての項目が必須入力です。"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "変更が保存されました。"
      redirect_to admin_item_path
    else
    flash.now[:alert] = "全ての項目が必須入力です。"
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :image, :name, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_lists_helper.rb
module Admin::OrderListsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/91d36909a5.js" crossorigin="anonymous"></script>
  </head>

  <body class="back-image">
    <div class="for-footer">
      <header>
          <!--#管理者がログイン状態-->
        <nav class="navbar navbar-expand navbar-dark bg-">
          <a href="/" ><img class="navbar-brand" src="/assets/logo_image.png" alt="logo" /></a>
          <% if admin_signed_in? %>
            <ul class="navbar-nav">
              <li class="navbar-item">
                <%= link_to "Sweets", admin_items_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "Customers", admin_customers_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "Orders", admin_orders_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "Genres", admin_genres_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "LogOut", destroy_admin_session_path, method: :delete, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <% if request.path == admin_orders_path %>
                <% elsif request.path == admin_genres_path %>
                  <p class="nav-p text-red"><%= alert %></p>
                <% else %>
                  <p class="nav-p"><%= notice %></p>
                  <p class="nav-p text-red"><%= alert %></p>
                <% end %>
              </li>
            </ul>

            <!--顧客のログイン状態-->
          <% elsif customer_signed_in? %>
            <ul class="navbar-nav">
              <li class="navbar-item">
                <%= link_to "MyPage", customers_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "Sweets", items_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "Cart", cart_items_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "LogOut", destroy_customer_session_path, method: :delete, class: "logo-font" %>
              </li>
              <li>

              </li>
              <li class="navbar-kuma">
                <img class="kumabaloon" src="/assets/baloon_left.png" />
              </li>
                <% if request.path == items_path %>
                  <p class="nav-p">ようこそ、<%= current_customer.last_name %>さん！</p>
                <% elsif request.path == customers_path %>
                  <p class="nav-p">ようこそ、<%= current_customer.last_name %>さん！</p>
                  <p class="nav-p text-red"><%= alert %></p>
                <% elsif request.path == root_path %>
                  <p class="nav-p">ようこそ、<%= current_customer.last_name %>さん！</p>
                <% else %>
                    <% if notice %>
                    <p class="nav-p"><%= current_customer.last_name %>さんへ、</p>
                    <p class="nav-p"><%= notice %></p>
                  <% elsif alert %>
                    <p class="nav-p"><%= current_customer.last_name %>さんへ、</p>
                    <p class="nav-p text-red"><%= alert %></p>
                  <% else %>
                    <p class="nav-p"><%= current_customer.last_name %>さんへ、</p>
                    <p class="nav-p">お買い物をお楽しみください♪</p>
                  <% end %>
                <% end %>
              <li class="navbar-kuma">
                <img class="kumabaloon" src="/assets/baloon_right.png" />
              </li>
              <li class="navbar-kuma">
                <img class="kumaimage" src="/assets/kuma_image.png" />
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav">
              <li class="navbar-item p-8">
                <%= link_to "About", homes_about_path, class: "logo-font" %>
              </li>
              <li class="navbar-item px-8">
                <%= link_to "Sweets", items_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "SignUp", new_customer_registration_path, class: "logo-font" %>
              </li>
              <li class="navbar-item">
                <%= link_to "LogIn", new_customer_session_path, class: "logo-font" %>
              </li>
            </ul>
            <!--ログインに失敗した時のエラーメッセージ-->
            <% if request.path == new_customer_session_path %>
            <% elsif request.path == new_customer_registration_path %>
            <% elsif request.path == new_admin_session_path %>
            <% elsif request.path == root_path %>
            <% else %>
              <% if notice %>
                <p class="nav-p"><%= notice %></p>
                <p class="nav-p text-red"><%= alert %></p>
              <% end %>
            <% end %>
            <!--ここまで-->
          <% end %>
        </nav>
      </header>

      <main>
        <%= yield %>
      </main>

      <footer>
          <p>© 2021 DMMWEBCAMP TeamComfort</p>
      </footer>
    </div>

  </body>
</html>